<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1541339837196" stop="1541339846526">
	<name>Test Automation of a banking app</name>
	<title>Test Automation of a banking app</title>
	<test-cases>
		<test-case start="1541339837197" stop="1541339846525" status="failed">
			<name>validate customer login test</name>
			<title>validate customer login test</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="db92f52c-47bc-465d-9d16-206c898af31f-attachment.png" type="image/png" size="26824"/>
			</attachments>
			<failure>
				<message>Expected &apos;Protractor practice website - Banking App&apos; to contain &apos;1Protractor practice&apos;.</message>
				<stack-trace>Error: Failed expectation
    at UserContext.&lt;anonymous&gt; (/home/ketan/WebstormProjects/TestSuites/Banking.js:8:36)
    at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
    at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
    at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>